# Generated by Django 2.2.12 on 2020-10-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messdetails',
            old_name='date',
            new_name='date_booked',
        ),
    ]
