# Generated by Django 2.2.12 on 2020-10-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0003_auto_20201002_1105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='MessUsers',
            new_name='MessUser',
        ),
    ]
