# Generated by Django 2.2.12 on 2020-10-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_auto_20201002_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='item_booked',
        ),
        migrations.AddField(
            model_name='booking',
            name='item_booked',
            field=models.ManyToManyField(to='mess.Item'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timings',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=100),
        ),
    ]
