# Generated by Django 2.2.12 on 2020-10-02 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0006_auto_20201002_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messstaff',
            old_name='mobile_no',
            new_name='unique_code',
        ),
        migrations.RemoveField(
            model_name='messstaff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messuser',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='messmember',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mess.MessStaff'),
        ),
        migrations.AddField(
            model_name='messstaff',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messstaff',
            name='username',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messuser',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messuser',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BasicUser',
        ),
    ]
